- name: Deploy tigera-operator
  shell: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.1/manifests/tigera-operator.yaml

- name: Download Calico custom-resources.yaml
  shell: wget -P /tmp https://raw.githubusercontent.com/projectcalico/calico/v3.27.1/manifests/custom-resources.yaml

- name: Patch CIDR to match cluster-cidr
  replace:
    path: /tmp/custom-resources.yaml
    regexp: 'cidr:.*'
    replace: 'cidr: 10.1.0.0/16'

- name: Apply custom Calico resources
  shell: kubectl apply -f /tmp/custom-resources.yaml

- name: Wait for Calico pods to be ready
  shell: |
    until kubectl get pods -n calico-system | grep calico-node | grep Running; do
      echo "Waiting for Calico to become ready..."
      sleep 10
    done
