openstack:
  cloud: overcloud
  region: RegionOne
  external_network: public
  keypair: talos-key
  key_file: /home/stack/.ssh/id_rsa.pub
  ubuntu_image_name: ubuntu
  talos_image_name: talos-1.11.0
  flavors:
    jump: medium
    controlplane: talos
    worker: talos

networking:
  net_name: talos-int-net-ans
  subnet:
    name: talos-int-subnet-ans
    cidr: 172.16.41.0/24
    gateway_ip: 172.16.41.1
    allocation_pool_start: 172.16.41.100
    allocation_pool_end: 172.16.41.200
  router_name: talos-router-ans


lb:
  name: talos-load-balancer-ans
  provider: ovn
  listener_name: talos-load-balancer-listener-ans
  pool_name: talos-load-balancer-pool-ans
  algorithm: SOURCE_IP_PORT
  protocol: TCP
  protocol_port: 6443
  healthmonitor:
    delay: 5
    max_retries: 4
    timeout: 10
    type: TCP
    name: talos-load-balancer-health-ans
  allocate_fip: true


security:
  jump_sg: jump-secgroup-ans
  talos_sg: talos-secgroup-ans
  allow_cidrs: ["0.0.0.0/0"]

ports:
  controller_prefix: talos-control-plane
  jump_port_name: jump-0

servers:
  jump_name: jump-0
  controller_count: 3
  worker_count: 3
  boot_from_volume: true
  volume_size_gb: 20
  assign_fip_to_controllers: false
  controller_float: true
  worker_float: false

kubeconfig: /home/ubuntu/.kube/config

talos_version: "1.11.0"
talos:
  cluster_name: talos-k8s-openstack
  version: "{{ talos_version }}"
  image_url: "https://factory.talos.dev/image/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba/v{{ talos_version }}/openstack-amd64.raw.xz"
  kube_api_port: 6443
  artifacts_dir: artifacts
  jump_user: ubuntu
  prefer_private_vip: false

