- name: Install kubectl (latest stable)
  ansible.builtin.shell: |
    set -euo pipefail
    if ! command -v kubectl >/dev/null 2>&1; then
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    fi
  args:
    executable: /bin/bash

- name: Retrieve kubeconfig to jump user's ~/.kube/config
  ansible.builtin.command: >
    talosctl --talosconfig {{ talos.artifacts_dir }}/talosconfig kubeconfig {{ kubeconfig }}

- name: Fetch kubeconfig back to control node artifacts
  ansible.builtin.fetch:
    src: "{{ kubeconfig }}"
    dest: "{{ talos.artifacts_dir }}/kubeconfig"
    flat: true

- name: Wait until node to be Ready
  shell: |
    until kubectl get nodes --no-headers | awk '{print $2}' | grep -v '^Ready$' | wc -l | grep 0; do
      echo "Waiting for nodes to be ready..."
      sleep 10
    done
