- name: Install kubectl (latest stable)
  ansible.builtin.shell: |
    set -euo pipefail
    if ! command -v kubectl >/dev/null 2>&1; then
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    fi
  args:
    executable: /bin/bash

- name: Retrieve kubeconfig to jump user's ~/.kube/config
  ansible.builtin.command: >
    talosctl --talosconfig {{ talos.artifacts_dir }}/talosconfig kubeconfig {{ kubeconfig }}

- name: Test kubectl connectivity
  ansible.builtin.command: kubectl get nodes -o wide
  register: nodes
  changed_when: false

- name: Print nodes
  ansible.builtin.debug:
    var: nodes.stdout_lines

- name: Fetch kubeconfig back to control node artifacts
  ansible.builtin.fetch:
    src: "{{ kubeconfig }}"
    dest: "{{ talos.artifacts_dir }}/kubeconfig"
    flat: true
