- name: Test kubectl connectivity
  ansible.builtin.command: kubectl get nodes -o wide
  register: nodes
  changed_when: false

- name: Print nodes
  ansible.builtin.debug:
    var: nodes.stdout_lines

- name: Fetch kubeconfig back to control node artifacts
  ansible.builtin.fetch:
    src: "{{ kubeconfig }}"
    dest: "{{ talos.artifacts_dir }}/kubeconfig"
    flat: true
